title: HARSHAD.N
description: HARSHAD Personal Website
baseurl: ""

username: HARSHAD.N
typing_text: Software Engineer / Backend Developer 

email: narshad.n4321@gmail.com
telegram_username: 
linkedin_username: harshad-n-070770205/
github_username: harshad4321
facebook_username: 
instagram_username: 
viber_number: 

show_aboutme_card: false
about_me_title: About Me
about_me_description: <empty>

show_skills_card: true
skills_title: Skills

show_timeline_card: true
timeline_title: Education & Experience
cv_download_link: https://resume.io/r/9zoIQb7A8

show_projects_card: true
show_projects: false
projects_title: Work Projects
show_os_projects: true
os_projects_title: Portfolio Projects

show_contact_card: true
contact_title: Contacts
contact_description: Feel free to contact me wherever is comfortable for you

repository: 
github_pages:
  - xx
  - xx
  - xx
  
projects:
  sort_by: stars
  exclude:
    archived: true
    forks: true
    projects:
      - xx

plugins:
  - "xxx"

exclude:
  [
    "_assets",
    "Gemfile",
    "Gemfile.lock",
    "gulpfile.js",
    "node_modules",
    "package.json",
  ]
